[package]
name = "akira"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "crates/akira-core", "crates/akira-memory-stream", "crates/akira-mqtt-stream"
]

[dependencies]
akira-core = { path = "crates/akira-core" }
akira-mqtt-stream = { path = "crates/akira-mqtt-stream" }
anyhow = "1.0"
ascii_table = "4.0"
async-trait = "0.1"
clap = { version = "3.1", features = ["derive"] }
diesel = { version = "1.4", features = ["postgres", "r2d2"] }
dotenv = "0.15.0"
handlebars = "4.3"
lazy_static = "1.3"
octocrab = { version = "0.16", default-features = false }
opentelemetry = { version = "0.17" }
opentelemetry-jaeger = { version = "0.16" }
prost = "0.10"
prost-types = "0.10"
tokio = { version = "1.14", features = ["fs", "macros", "rt", "rt-multi-thread"] }
tonic = "0.7"
tonic-web = "0.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["std", "env-filter"] }
tracing-opentelemetry = "0.17"
uuid = { version = "1.1", features = ["v4"] }

[dev-dependencies]
akira-memory-stream = { path = "crates/akira-memory-stream" }
futures = "0.3"

[profile.release]
lto = true

[lib]
name = "akira"
path = "src/service/lib.rs"

[[bin]]
name = "cli"
path = "src/cli/main.rs"

[[bin]]
name = "reconciler"
path = "src/reconciler/main.rs"

[[bin]]
name = "gitops"
path = "src/gitops/main.rs"

[[bin]]
name = "service"
path = "src/service/main.rs"
