#!/bin/bash

cargo update
cargo sqlx prepare
sqlx migrate run
cargo test --bins --tests --examples
cargo clippy --all-targets --all-features --workspace --no-deps -- -D warnings -A clippy::derive_partial_eq_without_eq
cargo fmt --all -- --check
rustup default nightly-2022-08-20
cargo udeps --all --all-targets
rustup default stable-aarch64-apple-darwin
cargo audit --ignore RUSTSEC-2020-0071 --ignore RUSTSEC-2021-0139
