name: Branch Deleted
on: delete
jobs:
  delete:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - uses: robinraju/release-downloader@v1.6
        with:
          repository: "fabriq-cloud/fabriq"
          latest: true
          fileName: "fabriq"

      - name: Delete api and gitops deployment for this branch
        run: |
          # Short name for current branch. For PRs, use target branch (base ref)
          GIT_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}

          chmod +x fabriq

          ./fabriq login ${{ secrets.GITHUB_TOKEN }}

          ./fabriq config delete deployment:${{ github.repository }}/gitops/$GIT_BRANCH:image
          ./fabriq deployment delete ${{ github.repository }}/gitops/$GIT_BRANCH

          ./fabriq config delete deployment:${{ github.repository }}/api/$GIT_BRANCH:image
          ./fabriq deployment delete ${{ github.repository }}/api/$GIT_BRANCH
