name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "tests/**"
      - "crates/**"
      - ".github/workflows/build-test.yaml"

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v1
      - name: Install diesel
        run: cargo install diesel_cli --no-default-features --features postgres
        id: diesel-install
      - name: Diesel migration
        run: diesel migration run
        id: diesel-migration
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Start Mosquitto MQTT Broker
        uses: namoshek/mosquitto-github-action@v1
        with:
          version: "1.6"
          ports: "1883:1883 8883:8883"
          container-name: "mqtt"
      - name: Test
        run: cargo test
        id: test
