name: Containerize API, Reconciler, and GitOps executables

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "proto/**"
      - "Cargo.lock"
      - "Dockerfile"
      - ".github/workflows/containerize-api.yaml"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata and create {branch}-{sha}-api tag
        id: api_meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-api
          tags: |
            type=sha,prefix=,format=long
      - name: Extract metadata and create {branch}-{sha}-reconciler tag
        id: reconciler_meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-reconciler
          tags: |
            type=sha,prefix=,format=long
      - name: Extract metadata and create {branch}-{sha}-gitops tag
        id: gitops_meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-gitops
          tags: |
            type=sha,prefix=,format=long
      - name: Build and Push Docker API image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: Dockerfile
          target: api
          push: true
          tags: ${{ steps.api_meta.outputs.tags }}
          labels: ${{ steps.api_meta.outputs.labels }}
      - name: Build and Push Docker Reconciler image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: Dockerfile
          target: reconciler
          push: true
          tags: ${{ steps.reconciler_meta.outputs.tags }}
          labels: ${{ steps.reconciler_meta.outputs.labels }}
      - name: Build and Push Docker Gitops image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: Dockerfile
          target: gitops
          push: true
          tags: ${{ steps.gitops_meta.outputs.tags }}
          labels: ${{ steps.gitops_meta.outputs.labels }}
