name: Dependency Audit
on:
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - ".github/workflows/dependency-audit.yaml"
  schedule:
    - cron: "0 0 * * *" # once a day at midnight UTC
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy, rustfmt
      - run: cargo audit --ignore RUSTSEC-2020-0071
      - run: rustup toolchain install nightly
      - run: cargo install cargo-udeps --locked
      - run: cargo +nightly udeps --all-targets
