on:
  push:
    tags:
      - "v*"

name: Release
jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@master
      - name: build x86_64-unknown-linux-musl
        run: |
          curl -LO "https://github.com/protocolbuffers/protobuf/releases/download/v3.20.3/protoc-3.20.3-linux-x86_64.zip"
          unzip protoc-3.20.3-linux-x86_64.zip -d /fabriq/protoc
          PATH="${PATH}:/fabriq/protoc"
          PROTOC="/fabriq/protoc/bin/protoc"
          SQLX_OFFLINE=true
          rustup target add x86_64-unknown-linux-musl
          apt update && apt install -y musl-tools musl-dev
          update-ca-certificates
          cargo build --target x86_64-unknown-linux-musl --release
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE.txt
            fabriq
