name: Static Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "tests/**"
      - "crates/**"
      - ".github/workflows/static-analysis.yaml"

env:
  CARGO_TERM_COLOR: always

jobs:
  static_code_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy, rustfmt
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v1
      - run: cargo clippy --all-targets --all-features --workspace --no-deps -- -D warnings
      - run: cargo fmt --all -- --check
      - name: Run doctest only
        # we run doctests here as cargo tarpaulin (our test runner)
        # requires nightly toolchain to do so
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --doc
      - name: Run cargo doc
        # This step is required to detect possible errors in docs that are not doctests.
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --workspace --no-deps # Warnings are treated as errors due to our .cargo/config file.
